version: '3'

networks:
  squid:

services:
  squid:
    image: sameersbn/squid:3.5.27-2
    networks:
      - squid
    ports:
      - 3128:3128
    volumes:
      - squid-cache:/var/spool/squid
    restart: always

volumes:
  squid-cache:
